coverage:
  round: down
  precision: 2
  status:
    project:
      default:
        threshold: 0.1%
        branches:
          - main
    patch:
      default:
        target: 90%
        branches:
          - main

