name: build-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:

    - name: Set up Go 1.19
      uses: actions/setup-go@v5
      with:
        go-version: ^1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Download dependencies
      run: go mod download

    - name: Verify formatting
      run: |
        unformatted=$(gofmt -l .)
        if [ -n "$unformatted" ]; then
          echo "These files are not gofmt-formatted:"
          echo "$unformatted"
          exit 1
        fi

    - name: Vet
      run: go vet ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -count=3 -v -coverprofile=coverage.out .

    - name: Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.out
        token: ${{ secrets.CODECOV_TOKEN }}